jacobi2d:
	export LD_LIBRARY_PATH=$(LD_LIBRARY_PATH):/home/guilherme/projetos/yask-learning
	g++ jacobi-client.cpp -std=c++14 -o jacobi-client -O2 -Wall -lyask_jacobi2d -I/home/guilherme/projetos/yask/include
